title: "traceprojector"
description: "Bounded, Commuting, Discrete-trace Preserving Projections"
theme: minima
logo: /assets/logo.svg
show_downloads: false
permalink: /:title/
plugins:
  - jekyll-feed
